name: "pipeline"

on:
  push:
    branches:
      - "*"
    tags:
      - "*"
    paths:
      - "jsr/**"
      - "npm/**"
      - "eng/**"
      - ".github/workflows/pipeline.yaml"
  pull_request:
    branches:
      - "*"
    paths:
      - "jsr/**"
      - "npm/**"
      - "eng/**"
      - ".github/workflows/pipeline.yaml"

  schedule:
    - cron: '12 11 * * *'

permissions:
  contents: write
  id-token: write

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - name: Install Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: Install Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: "22.x"

      - name: Bun Install
        run: bun install
        working-directory: npm

      - name: Deno Install
        run: deno install
        working-directory: jsr

      - name: Lint
        run: deno run -A ./eng/tasks/main.ts lint --all

      - name: Test
        run: deno run -A ./eng/tasks/main.ts test --all
        
      - name: Audit
        run: deno run -A ./eng/tasks/main.ts npm audit 

      - name: Npm Publish Dry Run
        run: deno run -A ./eng/tasks/main.ts npm publish --dry-run
        if: matrix.os == 'ubuntu-latest'

      - name: Publish Dry Run
        run: deno run -A ./eng/tasks/main.ts jsr publish --dry-run
        if: matrix.os == 'ubuntu-latest'

  release:
    needs: build
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    environment: production
    permissions:
      contents: write
      id-token: write
      discussions: write

    steps:
      - uses: actions/checkout@v4

      - name: Install Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: Install Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
          registriy-url: |
            https://registry.npmjs.org/

      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: "22.x"
          registry-url: 'https://registry.npmjs.org'

      - name: Bun Install
        run: bun install
        working-directory: npm


      - name: Deno Install
        run: deno install
        working-directory: jsr

      - name: "Build Changelog"
        id: github_release
        uses: mikepenz/release-changelog-builder-action@v6
        with:
          configuration: ".github/changelog.json"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: JSR Publish
        if: startsWith(github.ref, 'refs/tags/v')
        run: deno publish
        working-directory: ./jsr

      - name: NPM CI
        run: npm ci
        working-directory: ./npm

      - name: NPM Publish
        if: startsWith(github.ref, 'refs/tags/v')
        run: deno run -A ./eng/tasks/main.ts npm publish

      - name: Create GitHub Release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          release_name: ${{ github.ref_name }}
          body: ${{ steps.github_release.outputs.changelog }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
